const types = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    REGISTER: 'REGISTER',
    ADD_USER: 'ADD_USER',
    FETCH_USERS: 'FETCH_USERS',
    DELETE_USER: 'DELETE_USER',
    REAUTHENTICATE: 'REAUTHENTICATE'
}

export default types
