// constants
export const types = {
    ADD_LOG: 'ADD_LOG',
    DELETE_LOG: 'DELETE_LOG',
    UPDATE_LOG: 'UPDATE_LOG',
    FETCH_USER_LOGS: 'FETCH_USER_LOGS',
    FETCH_ALL_LOGS: 'FETCH_ALL_LOGS',
    STOP_FETCH_USER_LOGS: 'STOP_FETCH_USER_LOGS'
}